/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminView;

import adminControlers.AdminHomeControler;

/**
 *
 * @author darod
 */
public class AdminHomeWindow extends javax.swing.JFrame {

    private AdminHomeControler controler;

    /**
     * Creates new form AdminHomeWindow
     */
    public AdminHomeWindow() {
        initComponents();
        setLocationRelativeTo(null);
        controler = new AdminHomeControler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_manageDoctors = new javax.swing.JButton();
        bt_manageClients = new javax.swing.JButton();
        lb_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione la acción que desea realizar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        bt_manageDoctors.setText("Gestionar Doctores");
        bt_manageDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_manageDoctorsActionPerformed(evt);
            }
        });
        jPanel1.add(bt_manageDoctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        bt_manageClients.setText("Gestionar Clientes");
        bt_manageClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_manageClientsActionPerformed(evt);
            }
        });
        jPanel1.add(bt_manageClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        lb_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundAdmin.jpg"))); // NOI18N
        jPanel1.add(lb_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 299));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_manageDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_manageDoctorsActionPerformed
        controler.manegeWindow();

    }//GEN-LAST:event_bt_manageDoctorsActionPerformed

    private void bt_manageClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_manageClientsActionPerformed
        controler.registerWindow();

    }//GEN-LAST:event_bt_manageClientsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_manageClients;
    private javax.swing.JButton bt_manageDoctors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_background;
    // End of variables declaration//GEN-END:variables
}
