/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminView;

import Storage.Storage;
import Usuario.User;
import adminControlers.ClientInfoController;
import appointments.appointment;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author darod
 */
public class ClientInfoWindow extends javax.swing.JFrame {
    private User user;
    private Storage storage;
    private ClientInfoController controller;
    private DefaultTableModel dmApp;
    /**
     * Creates new form ClientInfoWindow
     * @param user user info to show
     * @param storage Where we get the list to show appointments
     */
    public ClientInfoWindow(User user, Storage storage) {
        initComponents();
        setLocationRelativeTo(null);
        this.user=user;
        this.storage=storage;
        dmApp = new DefaultTableModel();
        controller = new ClientInfoController();
        
        tb_appointments.setModel(dmApp);
        
        ta_clientInfo.setText(this.user.toString());
        bt_deleteAppointment.setEnabled(false);
        
//        addScheduleRow(user.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scroll1 = new javax.swing.JScrollPane();
        ta_clientInfo = new javax.swing.JTextArea();
        bt_enable = new javax.swing.JButton();
        bt_disableClient = new javax.swing.JButton();
        bt_addAppointment = new javax.swing.JButton();
        bt_deleteAppointment = new javax.swing.JButton();
        lb_title = new javax.swing.JLabel();
        scrollAppointments = new javax.swing.JScrollPane();
        tb_appointments = new javax.swing.JTable();
        bt_home = new javax.swing.JButton();
        lb_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ta_clientInfo.setEditable(false);
        ta_clientInfo.setColumns(20);
        ta_clientInfo.setRows(5);
        scroll1.setViewportView(ta_clientInfo);

        jPanel1.add(scroll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 330, 140));

        bt_enable.setText("Habilitar Cliente");
        bt_enable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enableActionPerformed(evt);
            }
        });
        jPanel1.add(bt_enable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        bt_disableClient.setText("Deshablilitar Cliente");
        bt_disableClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_disableClientActionPerformed(evt);
            }
        });
        jPanel1.add(bt_disableClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        bt_addAppointment.setText("Agregar Cita");
        bt_addAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addAppointmentActionPerformed(evt);
            }
        });
        jPanel1.add(bt_addAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        bt_deleteAppointment.setText("Eliminar Cita");
        bt_deleteAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteAppointmentActionPerformed(evt);
            }
        });
        jPanel1.add(bt_deleteAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        lb_title.setBackground(new java.awt.Color(255, 255, 255));
        lb_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setText("Información del Cliente");
        jPanel1.add(lb_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        tb_appointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollAppointments.setViewportView(tb_appointments);

        jPanel1.add(scrollAppointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 330, 140));

        bt_home.setText("Inicio");
        bt_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_homeActionPerformed(evt);
            }
        });
        jPanel1.add(bt_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        lb_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundAdmin.jpg"))); // NOI18N
        jPanel1.add(lb_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_enableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enableActionPerformed
        if(!user.isEnable()){
            user.setEnable(true);
            JOptionPane.showMessageDialog(null, "El cliente se ha habilitado");
        }else{
            JOptionPane.showMessageDialog(null, "El cliente ya está habilitado");
        }
    }//GEN-LAST:event_bt_enableActionPerformed

    private void bt_disableClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_disableClientActionPerformed
        if(user.isEnable()){
            user.setEnable(false);
            JOptionPane.showMessageDialog(null, "El cliente se ha deshabilitado");
        }else{
            JOptionPane.showMessageDialog(null, "El cliente ya está deshabilitado");
        }
    }//GEN-LAST:event_bt_disableClientActionPerformed

    private void bt_addAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addAppointmentActionPerformed
        controller.addAppointment(user,storage);
    }//GEN-LAST:event_bt_addAppointmentActionPerformed

    private void bt_deleteAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteAppointmentActionPerformed
        
    }//GEN-LAST:event_bt_deleteAppointmentActionPerformed

    private void bt_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_homeActionPerformed
        dispose();
    }//GEN-LAST:event_bt_homeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addAppointment;
    private javax.swing.JButton bt_deleteAppointment;
    private javax.swing.JButton bt_disableClient;
    private javax.swing.JButton bt_enable;
    private javax.swing.JButton bt_home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_background;
    private javax.swing.JLabel lb_title;
    private javax.swing.JScrollPane scroll1;
    private javax.swing.JScrollPane scrollAppointments;
    private javax.swing.JTextArea ta_clientInfo;
    private javax.swing.JTable tb_appointments;
    // End of variables declaration//GEN-END:variables

    private void addScheduleRow(String id) {
        ArrayList<appointment> list = storage.getActiveAppointments(id);
        dmApp.setRowCount(0);
        
        for (appointment object : list) {
            System.out.println(object.getDate());
            dmApp.addRow(object.toRow());
        }
        dmApp.fireTableDataChanged();
    }

}
