/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminView;

/**
 *
 * @author darod
 */
public class ClientInfoWindow extends javax.swing.JFrame {

    /**
     * Creates new form ClientInfoWindow
     */
    public ClientInfoWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ta_clientInfo = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        bt_enable = new javax.swing.JButton();
        bt_disableClient = new javax.swing.JButton();
        bt_addAppointment = new javax.swing.JButton();
        bt_deleteAppointment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lb_title = new javax.swing.JLabel();
        lb_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        ta_clientInfo.setViewportView(jTextArea1);

        jPanel1.add(ta_clientInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 330, 110));

        bt_enable.setText("Habilitar Cliente");
        jPanel1.add(bt_enable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        bt_disableClient.setText("Deshablilitar Cliente");
        jPanel1.add(bt_disableClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        bt_addAppointment.setText("Agregar Cita");
        jPanel1.add(bt_addAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        bt_deleteAppointment.setText("Eliminar Cita");
        jPanel1.add(bt_deleteAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 310, 110));

        lb_title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_title.setText("Información del Cliente");
        jPanel1.add(lb_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        lb_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundAdmin.jpg"))); // NOI18N
        jPanel1.add(lb_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addAppointment;
    private javax.swing.JButton bt_deleteAppointment;
    private javax.swing.JButton bt_disableClient;
    private javax.swing.JButton bt_enable;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lb_background;
    private javax.swing.JLabel lb_title;
    private javax.swing.JScrollPane ta_clientInfo;
    // End of variables declaration//GEN-END:variables
}
