/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminView;

/**
 *
 * @author darod
 */
public class DoctorRegisterWindow extends javax.swing.JFrame {

    /**
     * Creates new form DoctorRegisterWindow
     */
    public DoctorRegisterWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        lb_spec = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        cb_speciality = new javax.swing.JComboBox<>();
        bt_registerDoc = new javax.swing.JButton();
        lb_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_title.setBackground(new java.awt.Color(255, 255, 255));
        lb_title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_title.setText("Formulario de Registro de Doctores");
        jPanel1.add(lb_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lb_name.setBackground(new java.awt.Color(255, 255, 255));
        lb_name.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lb_name.setText("Nombre");
        jPanel1.add(lb_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, 20));

        lb_id.setBackground(new java.awt.Color(255, 255, 255));
        lb_id.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lb_id.setText("ID del Empleado");
        jPanel1.add(lb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        lb_spec.setBackground(new java.awt.Color(255, 255, 255));
        lb_spec.setText("Especialidad");
        jPanel1.add(lb_spec, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 160, -1));
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 160, -1));

        cb_speciality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cb_speciality, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 160, -1));

        bt_registerDoc.setText("Registrar Doctor");
        jPanel1.add(bt_registerDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        lb_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundAdmin.jpg"))); // NOI18N
        jPanel1.add(lb_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 300, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_registerDoc;
    private javax.swing.JComboBox<String> cb_speciality;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_background;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_spec;
    private javax.swing.JLabel lb_title;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
