/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminView;

import Storage.Storage;
import Usuario.User;
import appointments.appointment;
import appointments.schedule;
import doctor.doctor;
import java.util.ArrayList;

/**
 *
 * @author darod
 */
public class ScheduleAppointmentWindow extends javax.swing.JFrame {

    private Storage storage;
    private User user;

    /**
     * Creates new form ScheduleAppointmentWindow
     */
    public ScheduleAppointmentWindow(User user, Storage storage) {
        initComponents();
        setLocationRelativeTo(null);
        this.storage = storage;
        this.user = user;
        bt_schedule.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_schedules = new javax.swing.JLabel();
        scrollAppointments = new javax.swing.JScrollPane();
        jl_appoinments = new javax.swing.JList<>();
        scrollDoctors = new javax.swing.JScrollPane();
        jl_doctors = new javax.swing.JList<>();
        lb_title = new javax.swing.JLabel();
        bt_schedule = new javax.swing.JButton();
        bt_home = new javax.swing.JButton();
        lb_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_schedules.setBackground(new java.awt.Color(255, 255, 255));
        lb_schedules.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_schedules.setForeground(new java.awt.Color(255, 255, 255));
        lb_schedules.setText("Horarios disponibles");
        getContentPane().add(lb_schedules, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        jl_appoinments.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jl_appoinments.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jl_appoinmentsFocusGained(evt);
            }
        });
        scrollAppointments.setViewportView(jl_appoinments);

        getContentPane().add(scrollAppointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 200, 290));

        jl_doctors.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollDoctors.setViewportView(jl_doctors);

        getContentPane().add(scrollDoctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 470, 290));

        lb_title.setBackground(new java.awt.Color(255, 255, 255));
        lb_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setText("Selecione el medico con el que desee agendar");
        getContentPane().add(lb_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        bt_schedule.setText("Agendar");
        bt_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_scheduleActionPerformed(evt);
            }
        });
        getContentPane().add(bt_schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 353, -1, -1));

        bt_home.setText("Inicio");
        bt_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_homeActionPerformed(evt);
            }
        });
        getContentPane().add(bt_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 353, -1, -1));

        lb_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundAdmin.jpg"))); // NOI18N
        getContentPane().add(lb_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_homeActionPerformed
        dispose();
    }//GEN-LAST:event_bt_homeActionPerformed

    private void bt_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_scheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_scheduleActionPerformed

    private void jl_appoinmentsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jl_appoinmentsFocusGained
        bt_schedule.setEnabled(true);
    }//GEN-LAST:event_jl_appoinmentsFocusGained

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_home;
    private javax.swing.JButton bt_schedule;
    private javax.swing.JList<String> jl_appoinments;
    private javax.swing.JList<String> jl_doctors;
    private javax.swing.JLabel lb_background;
    private javax.swing.JLabel lb_schedules;
    private javax.swing.JLabel lb_title;
    private javax.swing.JScrollPane scrollAppointments;
    private javax.swing.JScrollPane scrollDoctors;
    // End of variables declaration//GEN-END:variables
}
