/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import doctor.doctor;
import java.util.ArrayList;

/**
 *
 * @author darod
 */
public class HomeWindow extends javax.swing.JFrame {
    /**
     * Creates new form HomeWindow
     */
    public HomeWindow() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bt_sched = new javax.swing.JButton();
        bt_cancelApp = new javax.swing.JButton();
        bt_history = new javax.swing.JButton();
        lb_indication = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_title.setForeground(new java.awt.Color(0, 0, 0));
        lb_title.setText("Bienvenido a nuestro sistema de Citas");
        getContentPane().add(lb_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 330, 70));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        bt_sched.setBackground(new java.awt.Color(0, 0, 0));
        bt_sched.setForeground(new java.awt.Color(255, 255, 255));
        bt_sched.setText("Agendar Citas");
        bt_sched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_schedActionPerformed(evt);
            }
        });

        bt_cancelApp.setBackground(new java.awt.Color(0, 0, 0));
        bt_cancelApp.setForeground(new java.awt.Color(255, 255, 255));
        bt_cancelApp.setText("Cancelar Citas");
        bt_cancelApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelAppActionPerformed(evt);
            }
        });

        bt_history.setBackground(new java.awt.Color(0, 0, 0));
        bt_history.setForeground(new java.awt.Color(255, 255, 255));
        bt_history.setText("Consultar Historial");
        bt_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_historyActionPerformed(evt);
            }
        });

        lb_indication.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_indication.setForeground(new java.awt.Color(0, 0, 0));
        lb_indication.setText("Por favor presione el botón de la accion a realizar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_indication, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(bt_sched)
                .addGap(38, 38, 38)
                .addComponent(bt_cancelApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(bt_history)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lb_indication, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_sched)
                    .addComponent(bt_cancelApp)
                    .addComponent(bt_history))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_historyActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryAppointmentWindow().setVisible(true);
            }
        });
    }//GEN-LAST:event_bt_historyActionPerformed

    private void bt_schedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_schedActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scheduleAppointmentWindow().setVisible(true);
            }
        });
    }//GEN-LAST:event_bt_schedActionPerformed

    private void bt_cancelAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelAppActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelAppointmentWindow().setVisible(true);
            }
        });
    }//GEN-LAST:event_bt_cancelAppActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelApp;
    private javax.swing.JButton bt_history;
    private javax.swing.JButton bt_sched;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_indication;
    private javax.swing.JLabel lb_title;
    // End of variables declaration//GEN-END:variables
}
